### ISSUE TITLE
api returns empty json

### ISSUE THREAD

**Issue by Yoonwoo** [qtuancr261/CryptocurrencyVisualization#1]
for some reason api on heroku doesnt work even though website does

**Comment by qtuancr261** [comment]
> for some reason api on heroku doesnt work even though website
Thanks for your watching :)) . My partner have a problem with the web service and it hasn't worked for 2 months. We are working on it to make it available soon.

**Comment by Yoonwoo** [comment]
Ok cool. I like your project, Qt is really good.
